title: Perses
  # email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about cyber security research, CTF writeups and much more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://persees.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 21perses
github_username:  persees

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-time-to-read
  - jekyll-seo-tag
  - jekyll-archives

minimal_mistakes_skin: "dark"

author:
  name: "perses"
  avatar: "/assets/images/sleep_glasses.png"
  bio: "Just a random guy blogging" # Note: Markdown is allowed
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://persees.github.io/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/21perses"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/persees"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/tiago-ventura-098529182/"


defaults:
  # all
  - scope:
      path: ""
    values:
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
        

search: true

# search engine verifications
google_site_verification: "oZU4zeLHY24FfT_tsL8EBB41Jbxdq9oNWNREXZpYjl0"

analytics:
    provider: "google-gtag"
    google:
        tracking_id: "G-XVYRWVR5H0"
        anonymize_ip: false # default

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
