title: Perses
  # email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about cyber security research, CTF writeups and much more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://persees.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 21perses
github_username:  persees

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-time-to-read

minimal_mistakes_skin: "dark"

author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am an **amazing** person." # Note: Markdown is allowed
  location: "Somewhere"
  links:
    - label: "Made Mistakes"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mmistakes"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      show_date: true
      breadcrumbs: true

